# Generated by Django 5.0.6 on 2024-06-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_date_created_stock_date_added_outgoingstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingstock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='incomingstock',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='incomingstock',
            name='warehouse',
        ),
    ]
