# Generated by Django 5.0.6 on 2024-10-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_vendor_tailor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='tailor',
        ),
    ]
