# Generated by Django 5.0.6 on 2024-10-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_product_cost_remove_stock_tailor'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingstock',
            name='code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
