# Generated by Django 5.0.6 on 2024-10-19 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_incomingstock_outgoing_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingstock',
            name='outgoing_stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_stocks', to='inventory.outgoingstock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomingstock',
            name='outgoing_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_stocks', to='inventory.outgoinglog'),
        ),
    ]
