# Generated by Django 5.0.6 on 2024-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_category_status_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='type',
            field=models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default='1', max_length=2),
        ),
    ]
