# Generated by Django 5.0.6 on 2024-06-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_production_type_alter_stock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='type',
        ),
    ]
