# Generated by Django 5.0.6 on 2024-06-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_incomingstock_outgoing_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production',
        ),
    ]
