# Generated by Django 5.0.6 on 2024-10-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_delete_production'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Tailor',
        ),
        migrations.RenameField(
            model_name='outgoinglog',
            old_name='vendor',
            new_name='tailor',
        ),
        migrations.RenameField(
            model_name='outgoingstock',
            old_name='vendor',
            new_name='tailor',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='vendor',
            new_name='tailor',
        ),
    ]
