# Generated by Django 5.0.6 on 2024-10-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_outgoingstock_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinglog',
            name='code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
