# Generated by Django 5.0.6 on 2024-10-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_outgoingstock_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoinglog',
            old_name='code',
            new_name='batch_code',
        ),
    ]
